#!/bin/bash
HEAD
 update_script
echo "ALX School"

echo "ALX School is so cool!"
 master

 HEAD
echo "ALX School is so cool!"
 HEAD


 dacf69d8e765a719239b348a5d27d53a779611ab
echo "ALX School"
 update_script
master
